name       : haskell-rio-prettyprint
version    : 0.1.1.0
release    : 1
source     :
    - https://hackage.haskell.org/package/rio-prettyprint-0.1.1.0/rio-prettyprint-0.1.1.0.tar.gz : 6e7abc8a179881bb612e64e393d8876a12b3de31ccac0dec98a6ba6b081509c0
license    : BSD-3-Clause
component  : programming.haskell
summary    : Pretty-printing for RIO
description: |
    Combine RIO's log capabilities with pretty printing
builddeps  :
    - haskell-annotated-wl-pprint-devel
    - haskell-ansi-terminal-devel
    - haskell-cabal-install
    - haskell-path-devel
    - haskell-rio-devel
rundeps    :
    - devel:
        - haskell-annotated-wl-pprint-devel
        - haskell-ansi-terminal-devel
        - haskell-path-devel
        - haskell-rio-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
